[package]
name = "pants-cleaner"
version = "0.1.0"
authors = ["C.Solovev <constantine.solovev@gmail.com>"]
edition = "2018"

[dependencies]

# CLI
structopt = "0.2.15"
# Serialization
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"